version: "3.8"
services:
   web:
       container_name: web
       build:
           context: . 
           dockerfile: Dockerfile.web
       ports:
           - 8000:80
       volumes:
           - "/projects/bgapp/web:/var/www/html:ro"
       networks:
           - app-network
       depends_on:
           - db
   db:
      container_name: db
      build:
          context: .
          dockerfile: Dockerfile.db
      networks:
          - app-network
      environment:
           MYSQL_ROOT_PASSWORD: "12345"
networks:
    app-network:
